- aubase410/gen_initializer.bal
- base/gen_initializer.bal
- uscore501/gen_initializer.bal
Move module initialization logs from info level to debug level in following packages.
- r4
- uscore501
- aubase410
Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1223
> Move module initialization logs from info level to debug level

- base/fhir_preprocessor.bal
- base/response_interceptors.bal
- fhirr4/ballerina/src/main/resources/fhirservice/http_service_builder.bal
* add content type in the response interceptor.
*  avoid allowing fhir+xml in accept and content type headers since it's not supported yet by our packages.
fixing: https://github.com/wso2-enterprise/open-healthcare/issues/1311
> Add response content type and remove validating fhir+xml

- .github/workflows/cd-fhirr4.yml
- .github/workflows/ci.yml
- .github/workflows/fhirr4-build-executor.yml
1) Added separate workflow for the fhirr4 as it uses maven build.
2) Changed the ci workflow so that it works with the maven build (it uses maven build for fhirr4 only and uses bal build for other packages). 
3) Added code so that the versions in the pom files of fhirr4 are updated instead of the version in ballerina.toml.
> Fixed issues in fhirr4 and ci workflows

- terminology/Dependencies.toml
- terminology/initializer.bal
- terminology/terminology.bal
- terminology/terminology_processor.bal
- terminology/tests/terminology_test.bal
- terminology/tests/terminology_test_utils.bal
Update imports for base FHIR resources
Base FHIR R4 resources such as `CodeSystem`, `ValueSet`, `Bundle`, `OperationOutcome` are packed with `ballerinax/health.fhir.r4`, instead the `ballerinax/health.fhir.r4.international401`. Therefore relevant imports need to be changed.
> Update imports for base FHIR resources

- .github/workflows/ci.yml
Using Github api to extract the list of files changed in a PR, returns paginated response. Hence directly using github graphql api to get all files.
> Extract all files from the PR

- r4/Dependencies.toml
- r4/errors.bal
Remove distinct keyword from FHIRError subtypes as it conflicts with the definition and usage of FHIRError subtypes.
> Remove distinct keyword from FHIRError subtypes

- fhirr4/ballerina/src/main/resources/fhirservice/fhir_preprocessor.bal
>$Subject. Currently our FHIR service fails to correctly process requests when some FHIR clients sends Accept header with multiple mime types.
>Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1511
> Fix errorneous Accept header handling for multiple mimetypes

- validator/validator.bal
> Add parsing for error messages returned by the backend, and re implemented createFHIRError of r4 inside the validator itself.
> For the backend to return user friendly error messages together with the original ones.
> The createFHIRError method was reimplemented as createValidationError inside the validator itself so that it's changes won't affect the r4. Created a new record FHIRValidationIssueDetail record which inherits  r4:FHIRIssueDetail.  Added a new field 'detailedErrors' inside FHIRValidationIssueDetail to hold the parsed error messages (the user friendly error messages).
Parsed the error messages returned by the backend and created a new set of error messages to be more user friendly which are stored in the instance of FHIRValidationIssueDetail .
> Add error message parsing for validator

- r4/Dependencies.toml
- r4/datatype_timing.bal
> Changed datatype of 'code' to 'CodeableConcept code?' due to an error when building PAS package.
> Add fix for PAS package generation issue

- fhirr4/ballerina/src/main/resources/fhirservice/core.bal
- fhirr4/ballerina/src/main/resources/fhirservice/http_service_builder.bal
- fhirr4/ballerina/src/main/resources/fhirservice/response_interceptors.bal
Fixing: https://github.com/wso2-enterprise/open-healthcare/issues/1300
* Added a map in the fhir ctx to hold properties.
* Extract the created resource id in the post path of the fhir service and set it as a property to fhir ctx.
* Get the location header property from the fhir ctx and set it to HTTP response in the response interceptor.
> Add location header when creating resources

- r4/fhir_implementation_guide.bal
- r4/fhir_registry.bal
> This PR includes a hotfix that makes the previously required `operations` field in `IGInfoRecord` (introduced in r4 v6.0.0) optional. Since this field can be made optional, it should be. Making this an optional field reduces dependent package breakages that might occur because of this change.
Related issues: https://github.com/wso2-enterprise/open-healthcare/issues/1593, https://github.com/wso2-enterprise/open-healthcare/issues/1592
> Make required 'operations' field in 'IGInfoRecord' in r4 optional

- .github/workflows/build-executor.yml
- .github/workflows/cd-fhirr4.yml
- .github/workflows/ci.yml
- .github/workflows/fhirr4-graalvm-check.yml
This PR updates the workflows to leverage the `setup-ballerina` action for managing Ballerina versions.
This change removes the previous usage of the `ballerina-action`.
> Use setup-ballerina for Ballerina versioning

- fhirr4/ballerina/pom.xml
- fhirr4/compiler-plugin/pom.xml
- fhirr4/native/pom.xml
- fhirr4/pom.xml
> This minor release fixes the dependency conflicts of fhirr4.
> [Release fhirr4 1.3.0] Prepare for release

- .github/workflows/build-executor.yml
- .github/workflows/ci.yml
- r4/Ballerina.toml
- r4/Dependencies.toml
> related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1644
The following packages will be migrated with this;
- health.fhir.r4
- health.fhir.international401
- health.fhir.parser
- health.fhir.fhirr4
> Migrate FHIR packages to Ballerina Update 10

- fhirr4/ballerina/src/main/resources/fhirservice/response_interceptors.bal
> Set custom response headers before responding back to client.
> To support `Content-Location` header for bulk export operation.
> https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4/pull/452
> Add custom headers from FHIRContext to response.

- uscore700/Ballerina.toml
- uscore700/Dependencies.toml
- uscore700/resource_uscore_questionnaire_response_profile.bal
- Resolves the need for more descriptive field names in `USCoreQuestionnaireResponseProfileItemAnswer`.
- Updates the type definition for `USCoreQuestionnaireResponseProfileQuestionnaire` to reflect the new type as `r4:uri`.
- Issue: https://github.com/ballerina-platform/ballerina-library/issues/7715
- Introduce more descriptive field names in `USCoreQuestionnaireResponseProfileItemAnswer` to improve code readability and maintainability.
- Update the type definition for `USCoreQuestionnaireResponseProfileQuestionnaire` to accurately represent it as a URI reference.
- Modified the `USCoreQuestionnaireResponseProfileItemAnswer` record to use more descriptive field names.
- Updated the documentation for `USCoreQuestionnaireResponseProfileQuestionnaire` to reflect the new type definition as …
> Update USCoreQuestionnaireResponseProfileQuestionnaire and USCoreQuestionnaireResponseProfileItemAnswer types

- fhirr4/ballerina/src/main/resources/fhirservice/http_service_builder.bal
> $subject
> Fix operation fetching issue
Logs from previous version
```
time=2025-04-21T12:24:16.051+05:30 level=DEBUG module=ballerinax/health.fhirr4 message="Request paths:  [\"fhir\",\"r4\",\"Group\",\"abc\",\"$export\"]"
time=2025-04-21T12:24:16.056+05:30 level=DEBUG module=ballerinax/health.fhirr4 message="Processing operation: roup"
time=2025-04-21T12:24:16.057+05:30 level=DEBUG module=ballerinax/health.fhirr4 message="Pre-processing FHIR operation : roup"
time=2025-04-21T12:24:16.091+05:30 level=DEBUG module=ballerinax/health.fhirr4 message="Execute: FHIR Response Error Interceptor"
```
Logs from fixed version
```
time=2025-04-21T13:38:52.917+05:30 level=DEBUG module=ballerinax/health.fhirr4 message="Request paths:  [\"fhir\",\"r4\",\"Group\",\"abc\",\"$export\"]" …
```
> Fix typo issue that causes incorrect substring index

- r4/Dependencies.toml
- r4/datatype_element.bal
This PR is related to [Parsing Error for Extended Element Arrays Inside Base Elements](https://github.com/ballerina-platform/ballerina-library/issues/7949). 
To fix the parsing error occurring, when there is an extended element array, instead of a plain element, in the second level of a base type.
The logics of the existing health-tool couldn't parse the below resource snippet from FHIR R5 ATCore (Austria) profiles. 
- Similar data fields were replicated in a FHIR R4 resource to check the possibility for such fields to be parsed correctly.
**NOTE:** Even though discovered from FHIR R5, there aren't any guarantee that FHIR R4 will totally be absent of such cases of field definitions. Therefore, the same change is transferred to FHIR R4 library too.
```
"address" : [{
"use" : "home",
"line" …
```
> [FHIR-R4-LIB] [Bug Fix] Parsing Error for Extended Element Arrays Inside Base Elements

- fhirr4/ballerina/pom.xml
- fhirr4/ballerina/src/main/resources/fhirservice/README.md
- fhirr4/ballerina/src/main/resources/fhirservice/analytics_request_interceptor.bal
- fhirr4/ballerina/src/main/resources/fhirservice/analytics_response_interceptor.bal
- fhirr4/ballerina/src/main/resources/fhirservice/http_service_builder.bal
- fhirr4/ballerina/src/main/resources/fhirservice/resources/analytics_README.md
- fhirr4/ballerina/src/main/resources/fhirservice/resources/analytics_more_info_api.yaml
- fhirr4/compiler-plugin/pom.xml
- fhirr4/native/pom.xml
- fhirr4/pom.xml
A new AnalyticsResponseInterceptor was added to intercept outgoing responses and publish logs asychronously to a configured server if enabled.
> $subject
- https://github.com/wso2-enterprise/open-healthcare/issues/1740
- Approach 3 in: https://github.com/wso2-enterprise/open-healthcare/issues/1750
> Ballerina: latest, Opensearch & Opensearch Dashboards: latest
> [Analytics] Add support to publish logs to a remote server

- fhirr4/ballerina/src/main/resources/fhirservice/fhir_preprocessor.bal
- fhirr4/ballerina/src/main/resources/fhirservice/listener.bal
- fhirr4/ballerina/src/main/resources/fhirservice/response_interceptors.bal
- fhirr4/ballerina/src/main/resources/fhirservice/tests/fhir_service_test.bal
- fhirr4/ballerina/src/main/resources/fhirservice/tests/test_service.bal
- fhirr4/ballerina/src/main/resources/fhirservice/utils.bal
- fhirr4/pom.xml
This PR introduces conditional create support to the FHIR service, aligning with the [FHIR R4 specification for conditional create](https://hl7.org/fhir/R4/http.html#ccreate). Conditional create allows clients to create a resource only if it does not already exist, based on search criteria provided in the If-None-Exist HTTP header.
- https://github.com/ballerina-platform/ballerina-library/issues/7978
- Enable the FHIR service to process conditional create requests.
- Prevent duplicate resource creation when a matching resource already exists.
- Return appropriate FHIR-compliant responses for all conditional create scenarios.
fhir_preprocessor.bal:
- Updated the processCreate function to check for the presence of the If-None-Exist header in incoming requests.
- If the header is present, …
> Add Conditional Create Support for FHIR Service

- fhirr4/ballerina/pom.xml
- fhirr4/ballerina/src/main/resources/fhirservice/listener.bal
- fhirr4/ballerina/src/main/resources/fhirservice/tests/fhir_service_test.bal
- fhirr4/compiler-plugin/pom.xml
- fhirr4/native/pom.xml
- fhirr4/pom.xml
> $Subject. This will enable the monolithic deployment where all the FHIR APIs will serve on the default http listener port.
> Add support for default listener for fhirr4 service

- fhirr4/ballerina/src/main/resources/fhirservice/fhir_preprocessor.bal
- To fix an `InherentTypeViolation` error that occurs when processing search parameters with missing or empty values in the `FHIRPreprocessor:processSearchParameters` function. The root cause was passing () (nil) instead of a `string[]` to the `decodeSearchParameterKey` function, which expects a non-nil array of strings for the values field.
- Prevents server errors and improves robustness when clients send search parameters without values.
> Fix InherentTypeViolation for Empty Search Parameter Values in FHIRPreprocessor

- r4/Dependencies.toml
- r4/core.bal
- r4/fhir_api_config.bal
- r4/fhir_registry.bal
This PR introduces FHIR services management capabilities to the `FHIRRegistry` and extends the `OperationConfig` type with additional configuration properties.
- Introduce service map to the FHIR registry to track the services with the resource type
- Add additional property to the `OperationConfig` in `ResourceApiConfig` to configure additional properties which relevant to the operations
- FHIR Services Management
- Added private field: `fhirServicesMap` to store FHIR service information by resource type
- New methods added:
- `addResourceFHIRService()` - Add a FHIR service to the registry
- `getResourceFHIRService()` - Retrieve a FHIR service by resource type
- `removeResourceFHIRService()` - Remove a FHIR service from the registry
- New type definition: `FHIRServicesCollection` for …
> Add FHIR services management and extend OperationConfig with additionalProperties

- terminology/Ballerina.toml
- terminology/Dependencies.toml
- terminology/inmemory_terminology.bal
- terminology/terminology.bal
- terminology/tests/terminology_test.bal
- terminology/tests/terminology_test_utils.bal
- terminology/utils.bal
This PR refactors terminology operations in the `ballerinax/health.fhir.r4.terminology` library to support database-connected terminology sources in addition to the existing in-memory model.
Resolves:
- https://github.com/ballerina-platform/ballerina-library/issues/7930
Updated Functions
- `codeSystemLookup()`: Rewritten to delegate code lookup to `findConcept(system, code)` defined in the terminology source abstraction.
- `valueSetLookup()`: Updated to fetch concepts using the unified retrieval mechanism for improved consistency and support for DB-backed value sets.
- `subsumes()`: Refactored to use backend-agnostic concept resolution logic.
Lookup functions now rely on the `findConcept()` method from the terminology source implementation instead of directly accessing CodeSystem.concept …
> Refactor terminology operations to support custom source implementations

- r4/datatype_address.bal
- r4/datatype_contact_point.bal
- r4/datatype_contributer.bal
- r4/datatype_contributor.bal
- r4/datatype_element_binding.bal
- r4/datatype_element_discriminator.bal
- r4/datatype_element_repeat.bal
- r4/datatype_element_slicing.bal
- r4/datatype_element_sort.bal
- r4/datatype_element_type.bal
- r4/datatype_human_name.bal
- r4/datatype_identifier.bal
- r4/datatype_narrative.bal
- r4/datatype_parameter_definition.bal
- r4/datatype_quantity.bal
**NOTE**: This issue was first detected by FHIR R5 IG parsing, the issue replicated in R4 as well due to tool changes thus breaking an existing R4 profile (USCore700). So, the fix was applied for R4 as well.
This PR fixes an issue where a child element cannot override the base datatype if it uses the same parameter name as the parent. Using the parent’s datatype may remove important characteristics of the child, and removing inheritance would break the relationship between the two elements.
For example, in the FHIR R5 international500 specification, consider the following:
```
public type ObservationbmiValue record {|
*r5:Quantity;
ObservationbmiValueComparator comparator?;
r5:Extension[] extension?;
string unit;
r5:code code = "kg/m2";
r5:uri system = "http://unitsofmeasure.org";
string …
```
> Add union operator for ENUM types
