- fhirr4/ballerina/pom.xml
- fhirr4/ballerina/src/main/resources/fhirservice/Ballerina.toml
- fhirr4/ballerina/src/main/resources/fhirservice/CompilerPlugin.toml
- fhirr4/ballerina/src/main/resources/fhirservice/Package.md
- fhirr4/ballerina/src/main/resources/fhirservice/externutils.bal
- fhirr4/ballerina/src/main/resources/fhirservice/fhir_service_holder.bal
- fhirr4/ballerina/src/main/resources/fhirservice/http_service.bal
- fhirr4/ballerina/src/main/resources/fhirservice/init.bal
- fhirr4/ballerina/src/main/resources/fhirservice/listener.bal
- fhirr4/ballerina/src/main/resources/fhirservice/type.bal
- fhirr4/ballerina/src/main/resources/fhirservice/utils.bal
- fhirr4/compiler-plugin/pom.xml
- fhirr4/compiler-plugin/src/main/java/io/ballerinax/fhirr4/compiler/Constants.java
- fhirr4/compiler-plugin/src/main/java/io/ballerinax/fhirr4/compiler/FHIRCompilerPlugin.java
- fhirr4/compiler-plugin/src/main/java/io/ballerinax/fhirr4/compiler/FHIRCompilerPluginUtil.java
- fhirr4/compiler-plugin/src/main/java/io/ballerinax/fhirr4/compiler/FHIRDiagnosticCodes.java
- fhirr4/compiler-plugin/src/main/java/io/ballerinax/fhirr4/compiler/FHIRResourceValidator.java
- fhirr4/compiler-plugin/src/main/java/io/ballerinax/fhirr4/compiler/FHIRServiceAnalyzer.java
- fhirr4/compiler-plugin/src/main/java/io/ballerinax/fhirr4/compiler/FHIRServiceValidator.java
- fhirr4/native/pom.xml
- fhirr4/native/src/main/java/io/ballerinax/fhirr4/ExecutionCallback.java
- fhirr4/native/src/main/java/io/ballerinax/fhirr4/HTTPToFHIRAdaptor.java
- fhirr4/native/src/main/java/io/ballerinax/fhirr4/ModuleUtils.java
- fhirr4/native/src/main/java/io/ballerinax/fhirr4/Utils.java
- fhirr4/pom.xml
> Move fhirr4 service type from internal to public repo

- README.md
- aubase410/Ballerina.toml
- aubase410/Dependencies.toml
- base/Ballerina.toml
- base/Dependencies.toml
- fhirr4/ballerina/src/main/resources/fhirservice/Ballerina.toml
- fhirr4/pom.xml
- uscore501/Ballerina.toml
- uscore501/Dependencies.toml
- utils/Ballerina.toml
- utils/Dependencies.toml
> $Subject
> https://github.com/wso2-enterprise/open-healthcare/issues/1243
> Upgrade Ballerina version to 2201.5.0

- fhirr4/ballerina/pom.xml
- fhirr4/ballerina/src/main/resources/fhirservice/Ballerina.toml
- fhirr4/ballerina/src/main/resources/fhirservice/utils.bal
- fhirr4/compiler-plugin/pom.xml
- fhirr4/native/pom.xml
- fhirr4/pom.xml
> Handle errors properly

- base/errors.bal
- base/request_interceptors.bal
- base/utils.bal
> Add a utility to get the error message

- base/datatype_element_date_filter.bal
- base/datatype_element_repeat.bal
- base/datatype_usage_context.bal
- base/fhir_parser.bal
- base/fhir_registry.bal
- base/utils.bal
- use of map.hasKey
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” …
> Sync codegen tool changes

- base/Dependencies.toml
- base/core.bal
- base/fhir_search_parameters_processors.bal
- base/utils.bal
- adds a utility method
- remove name field from the FHIRTypedSearchParameter as it duplicates the search param name
> Link(s) …
> Few improvements

- base/utils.bal
> Add utility methods to decode search params

- base/errors.bal
- base/fhir_parser.bal
Add error details in FHIRError
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1162
> Add error details in FHIRError

- r4/Ballerina.toml
- r4/Dependencies.toml
[Release r4 v4.0.0] Prepare for next dev cycle
> [Post] Release r4 v4.0.0

- r4/Module.md
- r4/utils.bal
Remove FHIRPath depedency from r4
> Remove FHIRPath depedency from r4

- r4/Ballerina.toml
- r4/Dependencies.toml
[Release r4 v4.0.0] Prepare for release
> [Release r4 v4.0.0] Prepare for release

- international401/Ballerina.toml
- international401/Dependencies.toml
- international401/Module.md
- international401/Package.md
[Release international401 v1.0.0] Prepare for release
> [Release international401 v1.0.0] Prepare for release

- r4/Ballerina.toml
- r4/Dependencies.toml
[Release r4 v4.0.0] Prepare for next dev cycle
> [Release r4 v4.0.0] Prepare for next dev cycle

- parser/fhir_parser.bal
> Resolve merge conflicts

- terminology/Ballerina.toml
- terminology/Dependencies.toml
[Release terminology v1.0.0] Prepare for release
> [Release terminology v1.0.0] Prepare for release

- international401/Ballerina.toml
- international401/Dependencies.toml
[Release international401 v1.0.0] Prepare for next dev cycle
> [Release international401 v1.0.0] Prepare for next dev cycle

- parser/Ballerina.toml
- parser/Dependencies.toml
- parser/Module.md
[Release parser v1.0.0] Prepare for release
> [Release parser v1.0.0] Prepare for release

- utils/ccdatofhir/Ballerina.toml
- utils/ccdatofhir/Dependencies.toml
- utils/ccdatofhir/Module.md
[Release ccdatofhir v1.0.0] Prepapre for release
> [Release ccdatofhir v1.0.0] Prepapre for release

- parser/Ballerina.toml
- parser/Dependencies.toml
- parser/Module.md
> Release parser v4.0.0

- utils/ccdatofhir/Ballerina.toml
- utils/ccdatofhir/Dependencies.toml
[Release ccdatofhir v1.0.0] Prepare for next dev cycle
> [Release ccdatofhir v1.0.0] Prepare for next dev cycle

- uscore501/Ballerina.toml
- uscore501/Dependencies.toml
[Release uscore501 v1.0.7] Prepare for release
> [Release uscore501 v1.0.7] Prepare for release

- parser/Ballerina.toml
- parser/Dependencies.toml
[Release parser v4.0.0] Prepare for next dev cycle
> [Release parser v4.0.0] Prepare for next dev cycle

- aubase410/Ballerina.toml
- aubase410/Dependencies.toml
- aubase410/Module.md
[Release aubase410 v1.0.7] Prepare for release
> [Release aubase410 v1.0.7] Prepare for release

- uscore501/Ballerina.toml
- uscore501/Dependencies.toml
[Release uscore v1.0.7] Prepare for next dev cycle
> [Release uscore v1.0.7] Prepare for next dev cycle

- validator/Ballerina.toml
- validator/Dependencies.toml
[Release validator v4.0.0] Prepare for release
> [Release validator v4.0.0] Prepare for release

- validator/Ballerina.toml
- validator/Dependencies.toml
[Release validator v4.0.0] Prepare for next dev cycle
> [Release validator v4.0.0] Prepare for next dev cycle

- fhirr4/ballerina/src/main/resources/fhirservice/Ballerina.toml
- fhirr4/pom.xml
[Release fhirr4 v1.0.7] Prepare for release
> [Release fhirr4 v1.0.7] Prepare for release

- terminology/Ballerina.toml
- terminology/Dependencies.toml
[[Release terminology v4.0.0] Prepare for release
> [Release terminology v4.0.0] Prepare for release

- terminology/Ballerina.toml
- terminology/Dependencies.toml
[Release terminology v4.0.0] Prepare for next dev cycle
> [Release terminology v4.0.0] Prepare for next dev cycle

- aubase410/Ballerina.toml
- aubase410/Dependencies.toml
[Release aubase v1.0.7] Prepare for next dev cycle
> [Release aubase v1.0.7] Prepare for next dev cycle

- international401/Ballerina.toml
- international401/Dependencies.toml
[Release international v1.0.0] Prepare for next dev cycle
> [Release international v1.0.0] Prepare for next dev cycle

- validator/Ballerina.toml
- validator/Dependencies.toml
[Release validator v4.0.0] Prepare for next dev cylcle
> [Release validator v4.0.0] Prepare for next dev cylcle

- fhirr4/pom.xml
[Release fhirr4 v1.0.7] Prepare for next dev cycle
> [Release fhirr4 v1.0.7] Prepare for next dev cycle

- r4/Ballerina.toml
- r4/Dependencies.toml
> Release r4 v4.0.0

- uscore501/Ballerina.toml
- uscore501/Dependencies.toml
- uscore501/Module.md
- uscore501/Package.md
- uscore501/initializer.bal
- uscore501/resource_uscore_goal_profile.bal
- uscore501/resource_uscore_pediatric_bmifor_age_observation_profile.bal
- uscore501/resource_uscore_pediatric_weight_for_height_observation_profile.bal
- uscore501/resource_uscore_provenance.bal
- uscore501/resource_uscore_pulse_oximetry_profile.bal
- uscore501/resource_uscore_vital_signs_profile.bal
> Release uscore501 v1.0.7

- aubase410/Ballerina.toml
- aubase410/Dependencies.toml
- aubase410/Module.md
- aubase410/Package.md
- aubase410/initializer.bal
- aubase410/resource_aubase_immunisation.bal
- aubase410/resource_aubase_practitioner.bal
- aubase410/resource_auhealth_program_participation_summary.bal
- aubase410/resource_aumedicine_list.bal
> Release aubase410 v1.0.7

- validator/Ballerina.toml
- validator/Dependencies.toml
- validator/Module.md
> Release validator v4.0.0

- utils/ccdatofhir/Ballerina.toml
- utils/ccdatofhir/Dependencies.toml
- utils/ccdatofhir/Module.md
> Release ccdattofhir v1.0.0

- fhirr4/ballerina/pom.xml
- fhirr4/ballerina/src/main/resources/fhirservice/Ballerina.toml
- fhirr4/compiler-plugin/pom.xml
- fhirr4/native/pom.xml
- fhirr4/pom.xml
> Release fhirr4 v1.0.7

- fhirr4/ballerina/src/main/resources/fhirservice/http_service_builder.bal
- r4/fhir_api_config.bal
- r4/fhir_authz_handler.bal
Fixing https://github.com/wso2-enterprise/open-healthcare/issues/1322
> Add support for calling an authz service in fhirr4

- .github/workflows/build-executor.yml
- .github/workflows/cd-aubase410.yml
- .github/workflows/cd-fhirr4.yml
- .github/workflows/cd-international401.yml
- .github/workflows/cd-parser.yml
- .github/workflows/cd-r4.yml
- .github/workflows/cd-terminology.yml
- .github/workflows/cd-uscore501.yml
- .github/workflows/cd-utils-ccdatofhir.yml
- .github/workflows/cd-utils-fhirpath.yml
- .github/workflows/cd-utils-patientmatching.yml
- .github/workflows/cd-validator.yml
- .github/workflows/ci.yml
> Added CI and CD workflows

- utils/patientmatching/Ballerina.toml
- utils/patientmatching/Dependencies.toml
> This PR includes the changes for patientmatching package release.
> [Release patientmatching v1.0.0] Prepare for release

- .github/workflows/ci.yml
- fhirr4/ballerina/src/main/resources/fhirservice/core.bal
- fhirr4/ballerina/src/main/resources/fhirservice/externutils.bal
- fhirr4/ballerina/src/main/resources/fhirservice/fhir_preprocessor.bal
- fhirr4/ballerina/src/main/resources/fhirservice/http_service_builder.bal
- fhirr4/compiler-plugin/src/main/java/io/ballerinax/fhirr4/compiler/Constants.java
- fhirr4/compiler-plugin/src/main/java/io/ballerinax/fhirr4/compiler/FHIRCompilerPluginUtil.java
- fhirr4/compiler-plugin/src/main/java/io/ballerinax/fhirr4/compiler/FHIRResourceValidator.java
- fhirr4/native/src/main/java/io/ballerinax/fhirr4/HTTPToFHIRAdaptor.java
- fhirr4/native/src/main/java/io/ballerinax/fhirr4/Utils.java
Fixing https://github.com/wso2-enterprise/open-healthcare/issues/1352
* Added the following interactions in the fhir service-
- vread
- update
- patch
- delete
- instance history
- type history
- metadata
* Added the following preprocessing - 
- update: validate payload, validate if the payload has the id and is the same as the id in the request
- patch: validate patch content types
- others: store necessary info in the fhir context
* Moved authz service call to the preprocessor
* Moved interaction records from health.fhir.r4 to health.fhirr4
* Fixed the issue of not supporting HTTP response as a return
* Added a fix to the CI workflow
> Add rest of the fhir interactions

- parser/Package.md
- parser/tests/parser_test.bal
- terminology/Package.md
- utils/fhirpath/Package.md
- utils/patientmatching/Dependencies.toml
- utils/patientmatching/Package.md
- validator/Package.md
> Update Package.md contents

- .github/workflows/ci.yml
- README.md
- fhirr4/ballerina/pom.xml
- fhirr4/ballerina/src/main/resources/fhirservice/Ballerina.toml
- fhirr4/ballerina/src/main/resources/fhirservice/tests/fhir_service_test.bal
- fhirr4/ballerina/src/main/resources/fhirservice/tests/test_api_config.bal
- fhirr4/ballerina/src/main/resources/fhirservice/tests/test_service.bal
- fhirr4/pom.xml
Adding tests with 72.76% coverage.
> Add fhir service tests

- utils/fhirpath/Module.md
- utils/fhirpath/fhir_path_client.bal
- utils/fhirpath/fhir_path_processor.bal
> This PR includes the changes for fix fhirpath to accept json as a input parameter instead of map<json>.
Related Issues : https://github.com/wso2-enterprise/open-healthcare/issues/1360
> Add fix to accept json as input for the fhirpath processor

- uscore501/Ballerina.toml
- uscore501/Dependencies.toml
- uscore501/Package.md
- uscore501/resource_uscore_allergy_intolerance.bal
- uscore501/resource_uscore_care_plan_profile.bal
- uscore501/resource_uscore_care_team.bal
- uscore501/resource_uscore_condition.bal
- uscore501/resource_uscore_diagnostic_report_profile_laboratory_reporting.bal
- uscore501/resource_uscore_diagnostic_report_profile_note_exchange.bal
- uscore501/resource_uscore_document_reference_profile.bal
- uscore501/resource_uscore_encounter_profile.bal
- uscore501/resource_uscore_goal_profile.bal
- uscore501/resource_uscore_immunization_profile.bal
- uscore501/resource_uscore_implantable_device_profile.bal
- uscore501/resource_uscore_laboratory_result_observation_profile.bal
- uscore501/resource_uscore_location.bal
- uscore501/resource_uscore_medication_profile.bal
- uscore501/resource_uscore_medication_request_profile.bal
- uscore501/resource_uscore_organization_profile.bal
- uscore501/resource_uscore_patient_profile.bal
- uscore501/resource_uscore_pediatric_bmifor_age_observation_profile.bal
- uscore501/resource_uscore_pediatric_weight_for_height_observation_profile.bal
- uscore501/resource_uscore_practitioner_profile.bal
- uscore501/resource_uscore_practitioner_role_profile.bal
- uscore501/resource_uscore_procedure_profile.bal
- uscore501/resource_uscore_provenance.bal
- uscore501/resource_uscore_pulse_oximetry_profile.bal
- uscore501/resource_uscore_smoking_status_profile.bal
- uscore501/resource_uscore_vital_signs_profile.bal
[Release uscore v1.1.0] Prepare for release
> [Release uscore v1.1.0] Prepare for release

- utils/ccdatofhir/Ballerina.toml
- utils/ccdatofhir/Dependencies.toml
- utils/ccdatofhir/ccda_to_fhir.bal
- utils/ccdatofhir/mapping_datatypes.bal
- utils/ccdatofhir/mapping_resource_allergy_intolerance.bal
- utils/ccdatofhir/mapping_resource_condition.bal
- utils/ccdatofhir/mapping_resource_diagnostice_report.bal
- utils/ccdatofhir/mapping_resource_immunization.bal
- utils/ccdatofhir/mapping_resource_medications.bal
- utils/ccdatofhir/mapping_resource_patient.bal
- utils/ccdatofhir/mapping_resource_practitioner.bal
- utils/ccdatofhir/mapping_resource_procedure.bal
Change IG of FHIR resources to USCore501
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1395
> Change IG of FHIR resources to USCore501

- utils/ccdatofhir/Ballerina.toml
- utils/ccdatofhir/Package.md
[Release ccdatofhir v1.0.1] Prepare for release
> [Release ccdatofhir v1.0.1] Prepare for release

- r4/Dependencies.toml
- r4/abstract_resource.bal
- r4/datatype_dosage.bal
Add Element ... to Resource record
- Add Element ... to Resource record
- Fix issues in Dosage datatype record
> Add Element ... to Resource record

- r4/constants.bal
- r4/datatype_reference.bal
Add create FHIR Reference method
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1211
> Add create FHIR Reference method

- r4/Ballerina.toml
- r4/Package.md
[Release r4 v4.1.1] Prepare for release
> [Release r4 v4.1.1] Prepare for release

- utils/fhirpath/Dependencies.toml
- utils/fhirpath/fhir_path_processor.bal
Add select resource elements method
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1265
> Add select resource elements method

- r4/fhir_registry.bal
Add base resource contexts to FHIRRegistry
> Add base resource contexts to FHIRRegistry

- r4/Package.md
[Release r4 v4.1.2] Prepare for release
> [Release r4 v4.1.2] Prepare for release

- r4/fhir_api_config.bal
- r4/fhir_audit_handler.bal
- r4/fhir_context.bal
- intro audit config
- a function to send audit events to the audit service
> Link(s) to product documentation that addresses …
> Introduce audit service integration changes

- r4/Package.md
[Release r4 v4.1.3] Prepare for release
> [Release r4 v4.1.3] Prepare for release

- .github/workflows/build-executor.yml
- .github/workflows/ci.yml
- r4/Dependencies.toml
- r4/core.bal
- r4/fhir_implementation_guide.bal
$subject and prepare for release
> [Release r4 v4.1.4] Remove unnecessary readonly type intersection

- r4/fhir_audit_handler.bal
- add audit event into the wrapper record
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
> Move the FHIR Error to a wrapper record

- r4/Dependencies.toml
- r4/Package.md
[Release r4 v4.1.4] Prepare for release
> [Release r4 v4.1.4] Prepare for release

- fhirr4/ballerina/src/main/resources/fhirservice/response_interceptors.bal
- fhirr4/pom.xml
- use Ballerina worker to send the audit events
- if sending fails, log the error along with the audit event
> Link(s) to …
> Call audit service asynchronously

- r4/fhir_audit_handler.bal
- Audit service client was initialized per request earlier. 
- method signature is changed to accept a http client for the audit service
> Audit client should be initialized once and use in sending audit events.

- r4/Package.md
> [Release r4 v4.1.5] Prepare for release

- fhirr4/ballerina/src/main/resources/fhirservice/response_interceptors.bal
- fhirr4/pom.xml
> Changes to audit event sending logic to pass the audit client

- uscore501/Ballerina.toml
- uscore501/resource_uscore_medication_request_profile.bal
> Fixes for uscore package with bal 8

- uscore501/Ballerina.toml
- uscore501/Dependencies.toml
> [Release uscore v1.2.0] Prepare for release

- r4/fhir_search_parameters_processors.bal
- r4/fhir_serializer.bal
- r4/type_utils.bal
>$Subject. 
> Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1446
> Migrate regex lib to regexp in r4

- fhirr4/ballerina/src/main/resources/fhirservice/fhir_preprocessor.bal
- r4/fhir_search_parameters_processors.bal
- r4/fhir_serializer.bal
- terminology/terminology_processor.bal
- utils/fhirpath/fhir_path_processor.bal
> $Subject.
> Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1446
> Migrate regex lib in terminology,fhirr4,fhirpath packages

- .github/workflows/build-executor.yml
- .github/workflows/cd-fhirr4.yml
- .github/workflows/ci.yml
- .github/workflows/fhirr4-graalvm-check.yml
- r4/Ballerina.toml
- r4/Dependencies.toml
> [Release r4 v4.2.0] Prepare for release

- parser/Ballerina.toml
- parser/Dependencies.toml
> [Release parser v4.1.0] Prepare for release

- validator/Ballerina.toml
- validator/Dependencies.toml
> [Release validator v4.1.0] Prepare for release

- r4/Dependencies.toml
- r4/datatype_extension.bal
Add inclusion type element for extensions
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1454
> Add inclusion type element for extensions

- utils/ccdatofhir/Ballerina.toml
- utils/ccdatofhir/Dependencies.toml
- utils/ccdatofhir/mapping_datatypes.bal
- utils/ccdatofhir/mappings_allergy_intolerance.bal
Fix issues in ccda-to-fhir lib
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1473
> Fix issues in ccda-to-fhir lib

- utils/ccdatofhir/mapping_datatypes.bal
Add fix for id extension mapping
> Add fix for id extension mapping

- lkcore010/datatypes.bal
Add new custom datatype to LKCore
> Add new custom datatype to LKCore

- utils/ccdatofhir/Dependencies.toml
- utils/ccdatofhir/mappings_medications.bal
Add fix for MedicationRequest issues
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1480
> Add fix for MedicationRequest issues

- utils/ccdatofhir/mappings_medications.bal
Fix mapping issues in MedicationRequest
- ".doNotPerform" = true
- ".addtionalInstruction" -> .additionalInstruction
> Fix issues

- r4/datatype_extension.bal
Fix issue in Extensions union
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1484
> Fix issue in Extensions union

- r4/Package.md
[Release r4 v4.3.1] Prepare for release
> [Release r4 v4.3.1] Prepare for release

- parser/Dependencies.toml
- parser/fhir_parser.bal
- parser/tests/parser_test.bal
- parser/tests/sample_resource_json_payloads.bal
- cover bunch of scenarios - code coverage increased from 41% to 83%
- fix the status codes
> Link(s) to product documentation …
> Add more test cases to the parser

- r4/Package.md
[Release r4 v4.3.2] Prepare for release
> [Release r4 v4.3.2] Prepare for release

- parser/Ballerina.toml
- parser/Dependencies.toml
- parser/fhir_parser.bal
- parser/tests/parser_test.bal
Fix test case invalid model type
> Fix test case invalid model type

- fhirr4/native/src/main/java/io/ballerinax/fhirr4/HTTPToFHIRAdaptor.java
- fhirr4/native/src/main/java/io/ballerinax/fhirr4/Utils.java
>$Subject
>Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1513
> Fix issue in defining FHIR operations

- utils/ccdatofhir/Dependencies.toml
- utils/ccdatofhir/mapping_datatypes.bal
- utils/ccdatofhir/mappings_allergy_intolerance.bal
- utils/ccdatofhir/mappings_condition.bal
- utils/ccdatofhir/mappings_diagnostice_report.bal
- utils/ccdatofhir/mappings_immunization.bal
- utils/ccdatofhir/mappings_medications.bal
- utils/ccdatofhir/mappings_patient.bal
- utils/ccdatofhir/mappings_practitioner.bal
- utils/ccdatofhir/mappings_procedure.bal
- utils/ccdatofhir/tests/test_mapping_allergy_intolerance.bal
- utils/ccdatofhir/tests/test_mapping_condition.bal
- utils/ccdatofhir/tests/test_mapping_datatypes.bal
- utils/ccdatofhir/tests/test_mapping_diagnostic_report.bal
- utils/ccdatofhir/tests/test_mapping_immunization.bal
- utils/ccdatofhir/tests/test_mapping_medication_request.bal
- utils/ccdatofhir/tests/test_mapping_patient.bal
- utils/ccdatofhir/tests/test_mapping_practitioner.bal
- utils/ccdatofhir/tests/test_mapping_procedure.bal
- utils/ccdatofhir/tests/test_utils.bal
- utils/ccdatofhir/tests/test_valid_ccda_document.xml
Add unit test cases for CCDA to FHIR package
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1475
> Add unit test cases for CCDA to FHIR package

- validator/Ballerina.toml
- validator/Dependencies.toml
- validator/validator.bal
> [Release validator v4.2.0] Prepare for release

- fhirr4/ballerina/src/main/resources/fhirservice/fhir_preprocessor.bal
> $Subject.
> Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1546
> Fix content type parameter handling issue

- fhirr4/ballerina/src/main/resources/fhirservice/externutils.bal
- fhirr4/ballerina/src/main/resources/fhirservice/http_service_builder.bal
- fhirr4/ballerina/src/main/resources/fhirservice/listener.bal
- fhirr4/native/src/main/java/io/ballerinax/fhirr4/HTTPToFHIRAdaptor.java
- fhirr4/native/src/main/java/io/ballerinax/fhirr4/Utils.java
Related Issue : https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4/issues/277
> Fix URL access for resources using r4:FHIRContext parameter

- fhirr4/ballerina/src/main/resources/fhirservice/http_service_builder.bal
- fhirr4/native/src/main/java/io/ballerinax/fhirr4/Utils.java
Related Issue : https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4/issues/277
> Fix path matching to include new request patterns

- terminology/Dependencies.toml
- terminology/terminology.bal
- terminology/terminology_processor.bal
- terminology/tests/resources/terminology/code_systems/account-status-invalid.json
- terminology/tests/resources/terminology/code_systems/account-status-without-url.json
- terminology/tests/resources/terminology/code_systems/account-status-without-version.json
- terminology/tests/resources/terminology/value_sets/account-status-incorrect.json
- terminology/tests/resources/terminology/value_sets/account-status-without-url.json
- terminology/tests/resources/terminology/value_sets/account-status-without-version.json
- terminology/tests/terminology_test.bal
> $Subject
> This will increase the code coverage to from 60% to 80%
> Improve unit tests for terminology

- validator/Dependencies.toml
- validator/tests/test.bal
- validator/validator.bal
Adding test cases with 100% coverage.
Also some changes to the validate method when handling xml and string payloads.
> Add validator tests

- validator/tests/test.bal
> Add test cases with 100% coverage
> Add tests with 100% coverage

- r4/Dependencies.toml
- r4/constants.bal
- r4/core.bal
- r4/fhir_api_config.bal
- r4/fhir_context.bal
- r4/variables.bal
Separating r4 changes from the following PRs:
https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4/pull/54
https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4/pull/104
> Add r4 changes for pagination and location header support 

- fhirr4/ballerina/pom.xml
- fhirr4/ballerina/src/main/resources/fhirservice/fhir_preprocessor.bal
- fhirr4/ballerina/src/main/resources/fhirservice/http_service_builder.bal
- fhirr4/ballerina/src/main/resources/fhirservice/tests/fhir_service_test.bal
- fhirr4/ballerina/src/main/resources/fhirservice/tests/pagination_test.bal
- fhirr4/ballerina/src/main/resources/fhirservice/tests/test_api_config.bal
- fhirr4/ballerina/src/main/resources/fhirservice/tests/test_service.bal
- fhirr4/ballerina/src/main/resources/fhirservice/utils.bal
- fhirr4/pom.xml
Fixing https://github.com/wso2-enterprise/open-healthcare/issues/1314
> Implement pagination support

- r4/Ballerina.toml
- r4/Dependencies.toml
> This major release introduces improvements and missing functionality for proper FHIR extended operations support.
> [Release r4 6.0.0] Prepare for release

- international401/Ballerina.toml
- international401/Dependencies.toml
- update dependencies
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” …
> Upgrade to bal9 international401

- .github/workflows/build-executor.yml
- .github/workflows/cd-fhirr4.yml
- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
- .github/workflows/fhirr4-graalvm-check.yml
- README.md
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1595
> Add daily Codecov upload workflow

- parser/Ballerina.toml
- parser/Dependencies.toml
> Upgread to bal 9 and dependency update

- .github/workflows/build-executor.yml
- .github/workflows/ci.yml
> Fixed Issues

- uscore501/Ballerina.toml
- uscore501/Dependencies.toml
- update dependencies
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” …
> Upgrade to bal9

- fhirr4/ballerina/src/main/resources/fhirservice/Ballerina.toml
- fhirr4/pom.xml
> Remove dependancies from Ballerina.toml so it will fetch the latest in the central.
fix: https://github.com/wso2-enterprise/open-healthcare/issues/1591
> Fix dependency version conflict

- parser/Ballerina.toml
- parser/Dependencies.toml
related:https://github.com/wso2-enterprise/open-healthcare/issues/1608
> Fix build failure of fhirr4 for ballerina 8
> release for r4 version bump[r4:6.0.1]

- .github/workflows/cd-fhirr4.yml
- .github/workflows/daily-build-fhirr4.yml
> Set bal central environment before maven build

- .github/workflows/cd-fhirr4.yml
- .github/workflows/daily-build-fhirr4.yml
> Bal 8 main

- utils/ccdatofhir/Dependencies.toml
- validator/Dependencies.toml
> Update dependencies for C-CDA and Validator packages
> Update Dependencies.toml for latest releases

- .github/workflows/cd-fhirr4.yml
- .github/workflows/daily-build-fhirr4.yml
- international401/Dependencies.toml
- parser/Dependencies.toml
- terminology/Dependencies.toml
- uscore501/Dependencies.toml
- utils/ccdatofhir/Dependencies.toml
- validator/Dependencies.toml
> [Parser]Sync with main

- international401/Dependencies.toml
- parser/Dependencies.toml
- terminology/Dependencies.toml
- uscore501/Dependencies.toml
> [Validator] Sync with main

- .github/workflows/cd-fhirr4.yml
- .github/workflows/daily-build-fhirr4.yml
- international401/Dependencies.toml
- parser/Dependencies.toml
- terminology/Dependencies.toml
- uscore501/Dependencies.toml
- utils/ccdatofhir/Dependencies.toml
- validator/Dependencies.toml
> [USCore501] Sync with main

- international401/Dependencies.toml
- parser/Dependencies.toml
- uscore501/Dependencies.toml
> [Terminology] Sync with main

- international401/Dependencies.toml
- parser/Dependencies.toml
- terminology/Dependencies.toml
- uscore501/Dependencies.toml
> [C-CDA] Sync with main

- r4/Ballerina.toml
- r4/Dependencies.toml
> Release r4 v5.1.0

- international401/Ballerina.toml
- international401/Dependencies.toml
> [Release international401 2.1.0] Prepare for next dev cycle

- utils/ccdatofhir/Ballerina.toml
- utils/ccdatofhir/Dependencies.toml
> [Release ccdatofhir 2.0.4] Prepare for next dev cycle

- fhirr4/ballerina/pom.xml
- fhirr4/compiler-plugin/pom.xml
- fhirr4/native/pom.xml
- fhirr4/pom.xml
> [Release fhirr4 1.3.1] Prepare for next dev cycle

- terminology/Ballerina.toml
- terminology/Dependencies.toml
> [Release terminology 4.1.1] Prepare for next dev cycle

- validator/Ballerina.toml
- validator/Dependencies.toml
> [Release validator 4.2.2] Prepare for next dev cycle

- .github/workflows/cd-aucore040.yml
- .github/workflows/daily-build-aubase421.yml
- .github/workflows/daily-build-aucore040.yml
> Add daily builds, rename workflow id

- cds/Package.md
> Update Package.md of cds module

- fhirr4/ballerina/src/main/resources/fhirservice/http_service_builder.bal
- fhirr4/native/src/main/java/io/ballerinax/fhirr4/HTTPToFHIRAdaptor.java
> $Subject.
> Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1623
> Add somedebug logs to the fhir native service adaptor

- cds/Ballerina.toml
- cds/Dependencies.toml
> $subject
> https://github.com/wso2-enterprise/open-healthcare/issues/1566
> [Release cds 1.0.0] Prepare for release

- cds/Ballerina.toml
- cds/Dependencies.toml
> $subject
> https://github.com/wso2-enterprise/open-healthcare/issues/1566
> [Release cds 1.0.0] Prepare for next dev cycle

- cds/records.bal
> Add more enums for CDS package

- .github/workflows/cd-davincihrex100.yml
- .github/workflows/daily-build-davincihrex100.yml
> Add CD workflow and daily build workflow for the davinci-hrex-100 package
> Add workflows for hrex package

- davincihrex100/Dependencies.toml
> Sync with main

- r4/fhir_api_config.bal
- r4/fhir_registry.bal
> $Subject
> Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1637
> Add custom search parameter support for fhir base

- fhirr4/ballerina/src/main/resources/fhirservice/fhir_preprocessor.bal
> $Subject.
> Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1637
> Add custom search parameter support for fhirservice

- fhirr4/native/src/main/java/io/ballerinax/fhirr4/HTTPToFHIRAdaptor.java
> Improve debug logging of native code

- .github/workflows/cd-carinbb200.yml
- .github/workflows/cd-davincipas.yml
- .github/workflows/daily-build-cds.yml
- .github/workflows/daily-build-davincipas.yml
- carinbb200/Dependencies.toml
- davincipas/Dependencies.toml
> Update dependency versions for carinbb200 and davincipas
> Add GitHub workflow for new modules
> Improvements

- carinbb200/Ballerina.toml
> [Release carinbb200 1.0.0] Prepare for next dev cycle

- .github/workflows/build-executor.yml
> Can't follow same CD pattern as HL7-V2 packages; hence reverting
> Revert workflow modification.

- international401/Ballerina.toml
- international401/Dependencies.toml
> Upgrade bal version of international package

- au/aubase410/Ballerina.toml
- au/aubase410/Dependencies.toml
- au/aubase421/Ballerina.toml
- au/aubase421/Dependencies.toml
- carinbb200/Ballerina.toml
- carinbb200/Dependencies.toml
- cds/Ballerina.toml
- cds/Dependencies.toml
- davincihrex100/Ballerina.toml
- davincihrex100/Dependencies.toml
- davincipas/Ballerina.toml
- davincipas/Dependencies.toml
- lkcore010/Ballerina.toml
- lkcore010/Dependencies.toml
- parser/Ballerina.toml
- parser/Dependencies.toml
- terminology/Ballerina.toml
- terminology/Dependencies.toml
- uscore501/Ballerina.toml
- uscore501/Dependencies.toml
- utils/ccdatofhir/Ballerina.toml
- utils/ccdatofhir/Dependencies.toml
- validator/Ballerina.toml
- validator/Dependencies.toml
> $subject
> the following packages will be migrated to Ballerina Update level 10
- aubase410
- aubase421
- carinbb200
- cds
- davincihrex100
- davincipas
- lkcore010
- parser
- terminology
- uscore501
- ccda-to-fhir
- validator
> Update bal version of FHIR packages

- .github/workflows/cd-fhirr4.yml
- .github/workflows/daily-build-executor.yml
> $subject
> Following workflows updated
- CD-FHIRR4
- DailyBuild Executor
> Update workflow bal version

- parser/Dependencies.toml
- terminology/Dependencies.toml
> There were few dependancies that are pointing to some old versions. Those are updated with this PR
> Update dependancy versions

- .github/workflows/cd-fhirr4.yml
- .github/workflows/daily-build-executor.yml
- fhirr4/ballerina/pom.xml
- fhirr4/compiler-plugin/pom.xml
- fhirr4/native/pom.xml
- fhirr4/pom.xml
- international401/Ballerina.toml
- international401/Dependencies.toml
- parser/Ballerina.toml
- parser/Dependencies.toml
- r4/Ballerina.toml
- r4/Dependencies.toml
- terminology/Dependencies.toml
- uscore501/Ballerina.toml
- uscore501/Dependencies.toml
- validator/Ballerina.toml
- validator/Dependencies.toml
> Sync with Main 

- r4/Ballerina.toml
- r4/Dependencies.toml
> `health.base` version is tend to get errors due to dependancy failure, updated dependancy toml will be synced with latest versions.
> Update base version

- parser/Dependencies.toml
- parser/Module.md
- parser/fhir_parser.bal
- parser/tests/parser_test.bal
- parser/tests/sample_resource_json_payloads.bal
- parser/validator.bal
> This will add another method called parseWithValidation.
> This will do the parsing and then apply the validation.
> https://github.com/wso2-enterprise/open-healthcare/issues/1665
> Add validation to the parser implementation

- r4/Ballerina.toml
- r4/Dependencies.toml
- r4/datatypes_primitive_types.bal
> https://github.com/wso2-enterprise/open-healthcare/issues/1664
> Add custom validation error messages to primitive data types

- .github/workflows/cd-uscore311.yml
- .github/workflows/cd-uscore400.yml
- .github/workflows/cd-uscore610.yml
- .github/workflows/cd-uscore700.yml
- .github/workflows/daily-build-uscore311.yml
- .github/workflows/daily-build-uscore400.yml
- .github/workflows/daily-build-uscore610.yml
- .github/workflows/daily-build-uscore700.yml
> $subject
> https://github.com/wso2-enterprise/open-healthcare/issues/1691
> Add CD workflow configs for newly added USCore profiles

- r4/Ballerina.toml
> Update the r4 release version

- uscore610/resource_uscore_patient_profile.bal
> Add missing field in gender record USCore 610

- uscore311/Dependencies.toml
- uscore400/Dependencies.toml
- uscore610/Dependencies.toml
- uscore700/Dependencies.toml
> Update the dependency.toml files of newly added USCore packages

- fhirr4/ballerina/src/main/resources/fhirservice/fhir_preprocessor.bal
- fhirr4/ballerina/src/main/resources/fhirservice/http_service_builder.bal
> $Subject.
> Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1031
> Add POST FHIR search support

- international401/resource_questionnaire.bal
> $subject
> https://github.com/wso2-enterprise/open-healthcare/issues/1700
> Add missing field to the Questionnaire record

- davincipas/Dependencies.toml
- davincipas/resource_pasclaim.bal
> $subject
> https://github.com/wso2-enterprise/open-healthcare/issues/1701
> Fix identifier array issue

- ips/Dependencies.toml
- ips/ips_bundle.bal
- ips/tests/ips_tests.bal
- ips/utils.bal
> Add holder data model for IPS bundle

- ips/Ballerina.toml
- ips/Dependencies.toml
- ips/tests/ips_tests.bal
- ips/utils.bal
- ips/variables.bal
> Add composition resource minimal mappings

- carinbb200/Dependencies.toml
- carinbb200/Package.md
- carinbb200/resource_c4bbcoverage.bal
- carinbb200/resource_c4bbexplanation_of_benefit.bal
- carinbb200/resource_c4bbexplanation_of_benefit_inpatient_institutional.bal
- carinbb200/resource_c4bbexplanation_of_benefit_oral.bal
- carinbb200/resource_c4bbexplanation_of_benefit_outpatient_institutional.bal
- carinbb200/resource_c4bbexplanation_of_benefit_pharmacy.bal
- carinbb200/resource_c4bbexplanation_of_benefit_professional_non_clinician.bal
- carinbb200/resource_c4bborganization.bal
- carinbb200/resource_c4bbpatient.bal
- carinbb200/resource_c4bbpractitioner.bal
- carinbb200/resource_c4bbrelated_person.bal
Update the Ballerina FHIR R4 Health `carinbb200` package to its latest version to ensure compatibility and leverage new features and improvements.
Ensure the package is up-to-date with the latest standards and improvements provided by the latest version of the `carinbb200` package.
Generate the package using ballerina health tool.
As a developer, I want to use the latest version of the `carinbb200` package to ensure my application is up-to-date with the latest standards and improvements.
Updated the Ballerina FHIR R4 Health `carinbb200` package to the latest version.
N/A
N/A
N/A
N/A
- Unit tests - N/A
- Integration tests - N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? …
> Update Ballerina FHIR R4 Health carinbb200 package to latest version

- .github/workflows/cd-fhirr4.yml
- .github/workflows/ci.yml
- .github/workflows/daily-build-fhirr4.yml
> Update workflows for fhirr4

- utils/ccdatofhir/Ballerina.toml
- utils/ccdatofhir/Dependencies.toml
- utils/ccdatofhir/ccda_to_fhir.bal
- utils/ccdatofhir/mapping_datatypes.bal
- utils/ccdatofhir/mappings_allergy_intolerance.bal
- utils/ccdatofhir/mappings_condition.bal
- utils/ccdatofhir/mappings_diagnostice_report.bal
- utils/ccdatofhir/mappings_immunization.bal
- utils/ccdatofhir/mappings_medications.bal
- utils/ccdatofhir/mappings_patient.bal
- utils/ccdatofhir/mappings_practitioner.bal
- utils/ccdatofhir/mappings_procedure.bal
> Add id gen logic and some missing reference fields

- .github/workflows/build-executor.yml
> Fix git workflow issue

- .github/workflows/build-executor.yml
- utils/ccdatofhir/Dependencies.toml
> Downgrade bal version

- .github/workflows/daily-build-fhirr4.yml
- .github/workflows/fhirr4-graalvm-check.yml
> Fix daily build failure

- .github/workflows/daily-build-fhirr4.yml
> Fix typo in java version in the workflow file.

- .github/workflows/cd-davincidtr210.yml
- .github/workflows/daily-build-davincidtr210.yml
> Add GitHub workflows for Davinci DTR package

- fhirr4/ballerina/pom.xml
- fhirr4/compiler-plugin/pom.xml
- fhirr4/native/pom.xml
- fhirr4/pom.xml
> $subject
> Reverting the manually bumped version
> Reverting the manually bumped fhirr4 version

- fhirr4/ballerina/src/main/resources/fhirservice/analytics_response_interceptor.bal
> $subject
> Fixing a bug in: https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4/pull/517
> [Analytics] Bug fix in configurable record

- parser/Ballerina.toml
- parser/Dependencies.toml
- parser/README.md
- parser/fhir_parser.bal
- parser/terminology_utils.bal
- parser/tests/Config.toml
- parser/tests/parser_test.bal
- parser/tests/sample_resource_json_payloads.bal
- parser/types.bal
- parser/validator.bal
PR to refactor the existing `parseWithValidation()` function in `health.fhir.r4.parser` to add terminology validation functionality to the validate operations.
> Refactor `health.fhir.r4.parser` Package to Add Terminology Validation

- parser/Ballerina.toml
- parser/Dependencies.toml
> [Release parser 6.1.0] Prepare for release

- ips/Ballerina.toml
- ips/Dependencies.toml
- Update the dependencies of the IPS package and bump the package version to major release.
> [IPS] Update dependencies and bump package version

- fhirr4/ballerina/pom.xml
- fhirr4/ballerina/src/main/resources/fhirservice/core.bal
- fhirr4/ballerina/src/main/resources/fhirservice/fhir_preprocessor.bal
- fhirr4/ballerina/src/main/resources/fhirservice/http_service_builder.bal
- fhirr4/ballerina/src/main/resources/fhirservice/listener.bal
- fhirr4/ballerina/src/main/resources/fhirservice/tests/fhir_service_test.bal
- fhirr4/ballerina/src/main/resources/fhirservice/tests/ips_generation_test.bal
- fhirr4/ballerina/src/main/resources/fhirservice/tests/test_api_config.bal
- fhirr4/ballerina/src/main/resources/fhirservice/tests/test_data.bal
- fhirr4/ballerina/src/main/resources/fhirservice/tests/test_service.bal
- fhirr4/ballerina/src/main/resources/fhirservice/utils.bal
- fhirr4/compiler-plugin/pom.xml
- fhirr4/native/pom.xml
- fhirr4/pom.xml
This PR introduces IPS (International Patient Summary) generation capability to the fhirr4 package. The implementation enables the FHIR server to process the $summary operation for the `Patient` resource, generating a compliant IPS Bundle as per the FHIR R4 specification. The changes include enhancements to the FHIR preprocessor, new logic for handling IPS-specific operations, and integration with the IPS context and section configuration.
To solve:
- https://github.com/wso2-enterprise/open-healthcare/issues/1776
- Enable the FHIR server to support the $summary operation for Patient resources, returning a standards-compliant IPS Bundle.
- Centralize and standardize the IPS generation logic within the FHIR preprocessor, ensuring maintainability and extensibility.
- Extended the …
> Add IPS (International Patient Summary) Generation Support to FHIR Service

- cds/Dependencies.toml
- cds/records.bal
- cds/tests/service_tests.bal
- cds/utils.bal
> Fix cds prefetch authorization

- r4/datatype_address.bal
- r4/datatype_contact_point.bal
- r4/datatype_contributer.bal
- r4/datatype_contributor.bal
- r4/datatype_element_binding.bal
- r4/datatype_element_discriminator.bal
- r4/datatype_element_repeat.bal
- r4/datatype_element_slicing.bal
- r4/datatype_element_sort.bal
- r4/datatype_element_type.bal
- r4/datatype_human_name.bal
- r4/datatype_identifier.bal
- r4/datatype_narrative.bal
- r4/datatype_parameter_definition.bal
- r4/datatype_quantity.bal
Reverts ballerina-platform/module-ballerinax-health.fhir.r4#555
> Revert "Add union operator for ENUM types"

- .github/workflows/daily-build-executor.yml
> $subject
> remove dependency.toml before bal build
> Verify package daily builds with latest dependency versions

- fhirr4/ballerina/src/main/resources/fhirservice/fhir_preprocessor.bal
- r4/Dependencies.toml
- r4/fhir_registry.bal
> $Subject. This will add custom operation registration support for FHIR API config.
> Add support for custom operation registration

- r4/Ballerina.toml
- r4/Dependencies.toml
> [Release r4 6.2.0] Prepare for release

- .github/workflows/daily-build-executor.yml
> fix: https://github.com/wso2-enterprise/open-healthcare/issues/1787
> fix dailybuild execution on forks

- utils/deidentify/Ballerina.toml
- utils/deidentify/Dependencies.toml
- utils/deidentify/README.md
- utils/deidentify/de-identify.bal
- utils/deidentify/operations.bal
- utils/deidentify/tests/test_bundle_deidentify.bal
- utils/deidentify/tests/test_deidentify.bal
- utils/deidentify/utils.bal
$subject
Related FHIR Path v3.0.0 changes: 
- https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4/pull/580
Related issue:
- https://github.com/wso2-enterprise/open-healthcare/issues/1761
> [DeIdentify] Support FHIRPath v3.0.0 & Refactor

- utils/fhirpath/Ballerina.toml
- utils/fhirpath/Dependencies.toml
- utils/fhirpath/README.md
- utils/fhirpath/tests/test_set_fhirpath_value_with_provided_function.bal
- utils/fhirpath/utils.bal
> [fhirpath] Generalize fhirpath:ModificationFucntionError to error

- utils/deidentify/Ballerina.toml
- utils/deidentify/Dependencies.toml
- utils/deidentify/README.md
- utils/deidentify/de-identify.bal
- utils/deidentify/operations.bal
- utils/deidentify/tests/test_deidentify.bal
- utils/deidentify/utils.bal
$subject
**Depends on:**
- https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4/pull/608
> [deidentify] Expose DeIdentificationFunction & DeIdentificationError instead fhirpath:ModificationFunction & fhirpath:ModificationFunctionError
